# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=64)),
                ('irida_project_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64)),
                ('folder', models.CharField(blank=True, max_length=256)),
                ('run_start_time', models.DateTimeField(auto_now=True)),
                ('run_end_time', models.DateTimeField(auto_now=True)),
                ('cluster_density', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('clusters_pf', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sequence_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sequdas.SequenceRun'),
        ),
    ]
