# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_type', models.CharField(blank=True, choices=[('READ_1', 'Read 1'), ('INDEX_1', 'Index 1'), ('INDEX_2', 'Index 2'), ('READ_2', 'Read 2')], max_length=32)),
                ('yield_gigabases', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('error_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('bases_greater_than_q30_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RenameField(
            model_name='sequencerun',
            old_name='clusters_pf',
            new_name='clusters_pf_percent',
        ),
        migrations.AddField(
            model_name='sample',
            name='index_1_i5_seq',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='sample',
            name='index_2_i7_seq',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='sample',
            name='reads_identified_pf_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sequencerun',
            name='bases_greater_than_q30_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencerun',
            name='reads_pf',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencerun',
            name='reads_total',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readsummary',
            name='sequence_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_summaries', to='sequdas.SequenceRun'),
        ),
    ]
