# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0002_auto_20171218_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='index_1_i5_seq',
            new_name='index_1_i7_seq',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='index_2_i7_seq',
            new_name='index_2_i5_seq',
        ),
        migrations.AlterField(
            model_name='sample',
            name='reads_identified_pf_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6),
        ),
    ]
