# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0003_auto_20171218_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequencerun',
            options={'permissions': (('view_sequence_run', 'View Sequence Run'),)},
        ),
    ]
