# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0004_auto_20171220_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'permissions': (('view_sample', 'View Sample'),)},
        ),
    ]
