# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0005_auto_20180210_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iem_file_version', models.CharField(max_length=8)),
                ('investigator_name', models.CharField(blank=True, max_length=64)),
                ('project_name', models.CharField(blank=True, max_length=64)),
                ('experiment_name', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField()),
                ('workflow', models.CharField(blank=True, max_length=64)),
                ('assay', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('chemistry', models.CharField(blank=True, max_length=64)),
                ('read1_length', models.IntegerField()),
                ('read2_length', models.IntegerField()),
                ('adapter', models.CharField(blank=True, max_length=128)),
                ('adapter_read_2', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SampleSheetSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=64)),
                ('sample_name', models.CharField(blank=True, max_length=64)),
                ('index_1_i7_seq', models.CharField(blank=True, max_length=16)),
                ('index_2_i5_seq', models.CharField(blank=True, max_length=16)),
                ('sample_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequdas.SampleSheet')),
            ],
        ),
    ]
