# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0006_samplesheet_samplesheetsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplesheet',
            name='application',
            field=models.CharField(blank=True, max_length=54),
        ),
        migrations.AddField(
            model_name='samplesheet',
            name='path',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='samplesheet',
            name='sequence_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_sheet', to='sequdas.SequenceRun'),
        ),
        migrations.AlterField(
            model_name='samplesheet',
            name='iem_file_version',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
