# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0007_auto_20180303_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplesheet',
            name='reverse_complement',
            field=models.NullBooleanField(),
        ),
    ]
