# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0008_samplesheet_reverse_complement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplesheet',
            old_name='adapter_read_2',
            new_name='adapter_read2',
        ),
    ]
