# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequdas', '0009_auto_20180303_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencerun',
            name='run_end_time',
        ),
        migrations.RemoveField(
            model_name='sequencerun',
            name='run_start_time',
        ),
        migrations.AlterField(
            model_name='sample',
            name='reads_identified_pf_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
