{% set name = "sequdas_server" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/dfornika/sequdas
  git_rev: develop

requirements:
  run:
  - python 3

test:
  commands:
    - sequdas_server.py -h

about:
  home: 
  license: 
  license_file: 
  summary:

